server:
  port: 9020

spring:
  application:
    name: ehouse-house-resouce-service
  servlet:
    multipart:
      max-request-size: 52128800
      max-file-size: 20MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.39.242:3306/ehouse?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
ribbon:
  #  建立连接所用时间，适用于网络正常的情况下，两端连接所用的时间
  ReadTimeout: 20000
  #建立连接后从服务器读取到可用资源的时间
  ConnectTimeout: 20000
eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka  单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: houseResouceprovider9020
    prefer-ip-address: true  #可以显示访问路径
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.minjiang.springcloud.entities  #所有Entity别名类所在包
