server:
  port: 9010

spring:
  application:
    name: ehouse-map-service


eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版
  instance:
    instance-id: map-9010
    prefer-ip-address: true