server:
  port: 80
eureka:
  client:
    #是否将自己注册到注册中心, 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: user-consumer80
    prefer-ip-address: true
spring:
  application:
    name: ehouse-user-consumer-service
      #设置允许 一个项目中有name一样的FeignClient
  main:
      allow-bean-definition-overriding: true
      #redis配置
  redis:
    host: 106.52.39.242
    port: 6379
    password:
    database: 1
    timeout: 60s
    ## springboot2.0之后将连接池由jedis改为lettuce
    lettuce:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10

#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      #采样率值介于0 到 1 之间， 1则表示全部采集
#      probability: 1
ribbon:
  #  建立连接所用时间，适用于网络正常的情况下，两端连接所用的时间
  ReadTimeout: 20000
  #建立连接后从服务器读取到可用资源的时间
  ConnectTimeout: 20000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.minjiang.ehouse.service.UserService: debug